### ISSUE TITLE
Best way to manage repo for pull request on official openhab2-addons?

### ISSUE THREAD

**Issue by lucacalcaterra** [lucacalcaterra/org.openhab.binding.melcloud#14]
I want to cleanup things for manage a near future pull request (for merging with offical openhab 2 addons).

Which is the best way to manage it ?

Leave this repo and  sync edits on a openhab2-addons fork , or transfer this repo directly on my fork of openhab2-addons ?

Who has enough experience on git and openhab development?

@paulianttila @thewiep ?

Thanks in advance...

**Comment by paulianttila** [comment]
I think you can't make PR from this repo, so you should freeze this and make PR from your openhab2-addon repo. You can open PR immediately and then just push you new commits to openhab2-addon/melcloud branch. If you are not happy about the code yet, just add [WIP] label to PR name to indicate that PR is still work in progress state.

**Comment by lucacalcaterra** [comment]
Ok i already created an openhab fork  with a melcloud branch... so i should lock this repo edits ?

**Comment by thewiep** [comment]
I checked the documentation on this a while ago here:
https://www.openhab.org/v2.3/docs/developer/development/bindings.html

and it seems if coding guidelines are met and you don't have any priority 1 issues (or relevant priority 2 and 3) you can create a PR.
There are only 3 priority 3 issues against style so an easy "fix".

I'm currently working on the implemenation for #13, if you lock this repo now can I rebase later on the other repo?

**Comment by lucacalcaterra** [comment]
I haven't so much confidence with git advanced commands, so... i need to test ... it's better to freeze this and migrate on my fork of openhab2-addons with melcloud branch ?

**Comment by thewiep** [comment]
Ok no worries. If it's done before you lock it I'll create a PR for this repo, if not I'll figure out what to do to get it in the other one :)

**Comment by lucacalcaterra** [comment]
@thewiep @paulianttila and other future collaborators, read...

I've created with MELCloud branch on a my forked of openhab2-addons repo at:
https://github.com/lucacalcaterra/openhab2-addons

I invite you to PR of your edits in that repository instead of this (which i'll mantain only for README... in future i could shutdown it)
