### ISSUE TITLE
AC Device shouldn't appear in the first discovery screen

### ISSUE THREAD

**Issue by lucacalcaterra** [lucacalcaterra/org.openhab.binding.melcloud#16]
The first time binding is configured , during autodiscovery, ac device shouldn't appear, but only the MELCloud account.

What do you think?

![image](https://user-images.githubusercontent.com/879825/64422485-81a81100-d0a4-11e9-824f-89c05b200d0e.png)

**Comment by thewiep** [comment]
It would indeed make sense to only get the device options once we already have a MELCloud Account configured.
I checked the docs but couldn't find any specific info on this.
If I understand correctly other bindings have implemented this with an additional DiscoveryService but would need to look into it further to understand how it actually works.
