### ISSUE TITLE
jar file never gets installed into openHAB

### ISSUE THREAD

**Issue by nuggit82** [lucacalcaterra/org.openhab.binding.melcloud#19]
When I download the jar file into the addons folder, nothing happens.

**Comment by thewiep** [comment]
This should work if you're on openHAB 2.5.
If you're on 2.4 you need to install the dependencies manually.

**Comment by nuggit82** [comment]
Are there any instructions how to do that?

**Comment by nuggit82** [comment]
I now installed openhab 2.5 and still the same result.

**Comment by thewiep** [comment]
Copying the file and checking permissions should be enough.
These are the instructions including correct locations to copy the .jar to:
https://www.openhab.org/docs/configuration/addons.html#through-manually-provided-add-ons
my .jar has 664 permissions

if it still doesn't show up you might try rebooting in case you haven't already.
Do you see anything in the openHAB log when copying the binding?

**Comment by nuggit82** [comment]
Hi, I looked at the logs in the var/log folder and nothing there thats added when the jar file is downloaded.

these are the permissions the file has
-rw-r--r-- 1 root    root    59927 aug  9 11:21 org.openhab.binding.melcloud-2.5.0-SNAPSHOT.jar
