### ISSUE TITLE
Communication error

### ISSUE THREAD

**Issue by ae-11** [lucacalcaterra/org.openhab.binding.melcloud#20]
Last 2 days I have "Status: OFFLINE - COMMUNICATION_ERROR Login error, reason: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $". 

I test MEL account (work) and rewrite credentials (correct) and got same result.

**Comment by thewiep** [comment]
Thanks for reporting, I just tested and am experiencing the same.
I'll have a look at it.

**Comment by lucacalcaterra** [comment]
Mine openhab doesn't report this error. Anyway thanks for opening the issue. Probably due to json structure change. thanks to @thewiep to check it

**Comment by ae-11** [comment]
OpenHAB restart resolve the problem... Sorry...

**Comment by thewiep** [comment]
I had the same issue in openHAB but could not reproduce it outside of openHAB.
I just restarted openHAB and it indeed works as expected again now.

@ae-11 glad you were able to work around it.
I grabbed some logs before I rebooted and will have another look to see what might have caused it but not sure if I'll be able to find anything.
I don't like stuff I can't explain :-)
