### ISSUE TITLE
add zone2 temperature

### ISSUE THREAD

**Issue by mkowalsk** [lucacalcaterra/org.openhab.binding.melcloud#21]
- Version used: openHAB 2.5.2, melcloud 2.5.2
- Operating System and version: synology

I am using the melcloud binding for my ecodan heatpump. Reading and setting the temperature for zone1 is working fine. It would be great to read and set the temperature for zone2.

Thank you very much for your work!

**Comment by lucacalcaterra** [comment]
@mkowalsk with much delay :-( anyway, i haven't an heatpump to test and develop it. So i'll close the issue
