### ISSUE TITLE
Horizontal Vane doesn't setting correctly

### ISSUE THREAD

**Issue by lucacalcaterra** [lucacalcaterra/org.openhab.binding.melcloud#3]
To Fix.

**Comment by thewiep** [comment]
Hi Luca,

I'm looking into this issue but I can't reproduce any issue with Horizontal Vane not setting correctly.
Perhaps recent changes in code fixed it?
Can you still reproduce this?
I did notice when setting Horizontal Vane to Swing, the response from MELCloud also sets Vertical Vane to Swing but upon the next refresh it goes back to the actual value.
I did the same test in the MELCloud webpage and the request and response where the same.
So if this is the issue, it's not the binding but the way MELCloud handles Swing.

**Comment by lucacalcaterra** [comment]
@thewiep Yes, not test accurately for report behiavour , but there's something wrong between melcloud state and ac state. So... we cannot fix on binding and then ... i can close this issue ?

**Comment by thewiep** [comment]
I think so since it's not really a bug.
It can be confusing for a user though so you might need to add it to the documentation.
