### ISSUE TITLE
[nternal.handler.MelCloudDeviceHandler] - No initial data available, ignore command

### ISSUE THREAD

**Issue by jfmennedy** [lucacalcaterra/org.openhab.binding.melcloud#9]
In Version 2.2 no commands are send . In karaf i got following message:

[nternal.handler.MelCloudDeviceHandler] - No initial data available, ignore command

**Comment by lucacalcaterra** [comment]
Thanks for feedback ! I'll check. Have you tried to rollback to a previous version? It works ?

**Comment by jfmennedy** [comment]
yes i rolled back to 2.1 and it works. i still have problems with polling.
if i do changings in melcloud app the changing appears not in openhab.

Am Fr., 5. Juli 2019 um 13:20 Uhr schrieb Luca Calcaterra <
notifications@github.com>:
